//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVenta.archivos.Idioma_en {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idioma_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idioma_en() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puntoVenta.archivos.Idioma_en.idioma-en", typeof(idioma_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a administration.
        /// </summary>
        internal static string administracion {
            get {
                return ResourceManager.GetString("administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password.
        /// </summary>
        internal static string clave {
            get {
                return ResourceManager.GetString("clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accounts receivable.
        /// </summary>
        internal static string cuentasPorCobrar {
            get {
                return ResourceManager.GetString("cuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a debts to pay.
        /// </summary>
        internal static string cuentasPorPagar {
            get {
                return ResourceManager.GetString("cuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a company.
        /// </summary>
        internal static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a billing.
        /// </summary>
        internal static string facturacion {
            get {
                return ResourceManager.GetString("facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a language.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string inicioDeSesion {
            get {
                return ResourceManager.GetString("inicioDeSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventory.
        /// </summary>
        internal static string inventario {
            get {
                return ResourceManager.GetString("inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a roster.
        /// </summary>
        internal static string nomina {
            get {
                return ResourceManager.GetString("nomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a options.
        /// </summary>
        internal static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
