//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVentaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_modulo_ventanas
    {
        public sistema_modulo_ventanas()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public int cod_modulo { get; set; }
        public string nombre_logico { get; set; }
        public string imagen { get; set; }
        public byte activo { get; set; }
    
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual sistema_modulo sistema_modulo { get; set; }
    }
}
