//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVentaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_ventanas
    {
        public sistema_ventanas()
        {
            this.sistema_modulo1 = new HashSet<sistema_modulo>();
        }
    
        public int codigo { get; set; }
        public string nombre_ventana { get; set; }
        public int cod_modulo { get; set; }
        public string nombre_logico { get; set; }
        public string imagen { get; set; }
        public bool activo { get; set; }
    
        public virtual sistema_modulo sistema_modulo { get; set; }
        public virtual ICollection<sistema_modulo> sistema_modulo1 { get; set; }
    }
}
