//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVenta.archivos.Idioma_en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idioma_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idioma_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puntoVenta.archivos.Idioma_en.idioma-en", typeof(idioma_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administration.
        /// </summary>
        internal static string administracion {
            get {
                return ResourceManager.GetString("administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string clave {
            get {
                return ResourceManager.GetString("clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts receivable.
        /// </summary>
        internal static string cuentasPorCobrar {
            get {
                return ResourceManager.GetString("cuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debts to pay.
        /// </summary>
        internal static string cuentasPorPagar {
            get {
                return ResourceManager.GetString("cuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        internal static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billing.
        /// </summary>
        internal static string facturacion {
            get {
                return ResourceManager.GetString("facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string inicioDeSesion {
            get {
                return ResourceManager.GetString("inicioDeSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory.
        /// </summary>
        internal static string inventario {
            get {
                return ResourceManager.GetString("inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roster.
        /// </summary>
        internal static string nomina {
            get {
                return ResourceManager.GetString("nomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        internal static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
