//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVenta.archivos.Idioma_es {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idioma_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idioma_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puntoVenta.archivos.Idioma_es.idioma-es", typeof(idioma_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administración.
        /// </summary>
        internal static string administracion {
            get {
                return ResourceManager.GetString("administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contraseña.
        /// </summary>
        internal static string clave {
            get {
                return ResourceManager.GetString("clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía.
        /// </summary>
        internal static string compania {
            get {
                return ResourceManager.GetString("compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por cobrar.
        /// </summary>
        internal static string cuentasPorCobrar {
            get {
                return ResourceManager.GetString("cuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por pagar.
        /// </summary>
        internal static string cuentasPorPagar {
            get {
                return ResourceManager.GetString("cuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación.
        /// </summary>
        internal static string facturacion {
            get {
                return ResourceManager.GetString("facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        internal static string inicioDeSesion {
            get {
                return ResourceManager.GetString("inicioDeSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        internal static string inventario {
            get {
                return ResourceManager.GetString("inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomina.
        /// </summary>
        internal static string nomina {
            get {
                return ResourceManager.GetString("nomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string opciones {
            get {
                return ResourceManager.GetString("opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
